### ISSUE TITLE
The request cannot be fulfilled due to bad syntax.

### ISSUE THREAD

**Issue by alexcroox** [CastawayLabs/cachet-monitor#28]
```
2016/03/07 22:06:23 /go/src/github.com/castawaylabs/cachet-monitor/cachet/monitor.go:84: https://example.com/ping 90.00% Down at 1457388383. Threshold: 80.00%
2016/03/07 22:06:23 /go/src/github.com/castawaylabs/cachet-monitor/cachet/monitor.go:93: Creating incident...
2016/03/07 22:06:23 /go/src/github.com/castawaylabs/cachet-monitor/cachet/incident.go:72: 400 {"errors":[{"id":"88f7de5f-37d9-4737-8f70-da1369c27c1b","status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax.","meta":{"details":["The status format is invalid."]}}]}
2016/03/07 22:06:23 /go/src/github.com/castawaylabs/cachet-monitor/cachet/incident.go:85: Could not create/update incident!
2016/03/07 22:06:28 /go/src/github.com/castawaylabs/cachet-monitor/cachet/monitor.go:84: https://example.com/ping 100.00% Down at 1457388388. Threshold: 80.00%
```

```
2016/03/07 22:07:28 /go/src/github.com/castawaylabs/cachet-monitor/cachet/monitor.go:84: https://example.com/ping 70.00% Down at 1457388448. Threshold: 80.00%
2016/03/07 22:07:28 /go/src/github.com/castawaylabs/cachet-monitor/cachet/monitor.go:114: Updating incident to resolved...
2016/03/07 22:07:28 /go/src/github.com/castawaylabs/cachet-monitor/cachet/incident.go:72: 400 {"errors":[{"id":"f95b7980-d9e9-4930-9576-dafed3dce1cf","status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax.","meta":{"details":["The status format is invalid."]}}]}
2016/03/07 22:07:28 /go/src/github.com/castawaylabs/cachet-monitor/cachet/incident.go:85: Could not create/update incident!
2016/03/07 22:07:33 /go/src/github.com/castawaylabs/cachet-monitor/cachet/monitor.go:84: https://example.com/ping 60.00% Down at 1457388453. Threshold: 80.00%
```

However it does appear to create the incident:

![SS](http://cl.ly/fLU9/d)

**Comment by ankush-grover-3pg** [comment]
I am also getting the same error and the incident is getting created. And while updating the status on the previous incident a new incident is created with the "Fixed"  Status.

Error while creating the incident:

2016/03/08 10:26:59 [$GOPATH]/github.com/castawaylabs/cachet-monitor/cachet/incident.go:72: 400 {"errors":[{"id":"ae35a6d9-d097-4c87-bab8-d1c8e9fbf60d","status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax.","meta":{"details":["The status format is invalid."]}}]}

Error while updating the incident.
[$GOPATH]/github.com/castawaylabs/cachet-monitor/cachet/incident.go:72: 400 {"errors":[{"id":"bf5dc744-e156-4fa3-beea-5542500e75d1","status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax.","meta":{"details":["The status format is invalid."]}}]}

My /etc/cachet-montior.config.json

{
  "api_url": "[URL]",
  "api_token": "[Token]",
  "interval": 5,
  "monitors": [
    {
      "name": "[Name]",
      "url": "[URL]",
      "metric_id": 0,
      "threshold": 80,
      "component_id": 1,
      "expected_status_code": 200,
      "strict_tls": false 
    }
  ],
  "insecure_api": true
}

**Comment by Echobob** [comment]
Hi guys,
I belive there's been some updates to cachet. We'll look into this.

@ankush-grover-3pg Careful when posting to github! You had both your IP and your API token in you post. I've removed them.

**Comment by ankush-grover-3pg** [comment]
Hi Echobob,

Thanks for the Update.

I am aware that the IPs and API token were there. They are from the docker test environment not accessible to the outside world. Thanks anyway

**Comment by paul-henriz** [comment]
Hi guys,

I've the same problem.
Ping and status change work, but it doesn't create incident.
Any fix ?
Thank you in advance

**Comment by maitrey0da** [comment]
Hi,

Same problem here

**Comment by matejkramny** [comment]
I have published some changes that may fix this. Can you check if you still have the problem?

Thanks!

**Comment by tomtom125** [comment]
Hi, 
I have the same problem.
Status change works.

New incident error:
Creating incident...
2018/06/27 12:25:50 /go/src/github.com/castawaylabs/cachet-monitor/cachet/incident.go:72: 400 {"errors":[{"id":"7xxxxxxx3","status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax.","meta":{"details":["The status format is invalid."]}}]}
2018/06/27 12:25:50 /go/src/github.com/castawaylabs/cachet-monitor/cachet/incident.go:85: Could not create/update incident!

Incident resolved error:
2018/06/27 12:26:50 /go/src/github.com/castawaylabs/cachet-monitor/cachet/monitor.go:114: Updating incident to resolved...
2018/06/27 12:26:50 /go/src/github.com/castawaylabs/cachet-monitor/cachet/incident.go:72: 400 {"errors":[{"id":"5dxxxxxxxxxxxxxxxxx7f9","status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax.","meta":{"details":["The status format is invalid."]}}]}
2018/06/27 12:26:50 /go/src/github.com/castawaylabs/cachet-monitor/cachet/incident.go:85: Could not create/update incident!


 I'm using : cachethq/docker:2.3.14 and castawaylabs/cachet-monitor docker images

Can you help me?
Thanks
Tom
