### ISSUE TITLE
Measure uptime

### ISSUE THREAD

**Issue by ghost** [CastawayLabs/cachet-monitor#73]
How do I measure uptime?

**Comment by spiritix** [comment]
Is this repository still maintained? This would be a must-have feature...

**Comment by matejkramny** [comment]
You may be misunderstanding what this tool is for. The purpose of this tool is to be a geographically distributed program that tests uptime and reports this to cachet.

Measuring uptime is unsuitable because it doesn't work on a bigger scale. This is cachet's problem in a way since this reports to cachet and that's all it cares about.

There's a potential for a spinoff project that has a central database and receives "server is up/down" from cachet-monitor.

**Comment by spiritix** [comment]
Agree, this is something Cachet should offer
